import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ParticleContainer } from '@/components/particle-container'
import { Header } from '@/components/header'
import { cn } from '@/lib/utils'
import { Footer } from '@/components/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "bg-[#00000e] text-white")}>
        <Header />
        {children}
        <Footer />
        <ParticleContainer />
      </body>
    </html>
  )
}
